name: Update Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          filename: github.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: MrWooltrest
          template: classic
          base: header, repositories
          config_timezone: Europe/Kiev
          plugin_lines: yes
        #name: Current year calendar
      #- uses: lowlighter/metrics@latest
        #with:
          #filename: github.metrics.calendar.svg
          #token: ${{ secrets.METRICS_TOKEN }}
          #base: ""
          #plugin_calendar: yes

